version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.production
    ports:
      - "20000:5432"
    volumes:
      - pig-bot_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    restart: always
    depends_on:
      - database
    networks:
      - default
volumes:
  pig-bot_data:
    external: true